"""Generate src/components/terminalLogoPaths.js from the web-ready logo SVG.

Re-run from the repo root to change the hover command:  python3 scripts/build-terminal-logo.py "cd /home"
Needs fonttools (pip install fonttools) and CourierPrime-Bold.ttf in the repo root
(github.com/quoteunquoteapps/CourierPrime, fonts/ttf). Not needed at runtime.
"""
import re, sys
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

COMMAND = sys.argv[1] if len(sys.argv) > 1 else 'cd /home'
LOGO = 'public/assets/brand/suddennorth-terminal.svg'
FONT = 'CourierPrime-Bold.ttf'
OUT = 'src/components/terminalLogoPaths.js'

svg = open(LOGO).read()
prompt = re.search(r'id="prompt"[^>]*d="([^"]+)"', svg).group(1)
word = re.search(r'id="wordmark"[^>]*d="([^"]+)"', svg).group(1)

font = TTFont(FONT); gs = font.getGlyphSet(); cmap = font.getBestCmap(); hmtx = font['hmtx']
s = 72.554 / font['head'].unitsPerEm
CURSOR_X, BASE_Y = 616.146, 57.303
adv = hmtx[cmap[ord('a')]][0] * s           # monospace advance (≈43.53)

chars = []
for i, ch in enumerate(COMMAND):
    if ch == ' ':
        chars.append(None); continue
    pen = SVGPathPen(gs, ntos=lambda v: f'{v:.2f}'.rstrip('0').rstrip('.'))
    gs[cmap[ord(ch)]].draw(TransformPen(pen, (s, 0, 0, -s, CURSOR_X + i * adv, BASE_Y)))
    chars.append(pen.getCommands())

js = f"""// Generated by scripts/build-terminal-logo.py — outlined Courier Prime Bold, no font needed at runtime.
// The hover command below is pre-outlined; re-run the script to change it.
export const VIEWBOX = '0 0 640.035 76.575';
export const CURSOR = {{ x: 616.146, y: 9.653, width: 23.889, height: 47.778 }};
export const CHAR_ADVANCE = {adv:.4f};
export const COMMAND = {COMMAND!r};
export const PROMPT_PATH = '{prompt}';
export const WORDMARK_PATH = '{word}';
// One entry per character of COMMAND (null = space), already positioned after the wordmark.
export const COMMAND_PATHS = [
{chr(10).join(('  null,' if c is None else f"  '{c}',") for c in chars)}
];
"""
open(OUT, 'w').write(js)
print('wrote', OUT, len(js), 'bytes; command spans to x =', CURSOR_X + len(COMMAND) * adv + 23.889)
